# Generated by Django 5.0 on 2023-12-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInput', models.CharField(max_length=100000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
